package: cheatsheet
version: '0.0.1'
author: Thomas Blum
supportpage: www.redaxo.org/de/forum/

load: late

page:
    title: 'translate:cheatsheet'
    perm: cheatsheet[]
    pjax: false
    icon: rex-icon fa fa-medkit

providers:
    - Cheatsheet\ExtensionPoint\ExtensionPointServiceProvider
    - Cheatsheet\RexVar\RexVarServiceProvider

stylesheets:
    - cheatsheet.css
